---
title: "NHS-R Community Fellowships"
format: html
editor: 
  markdown: 
    wrap: 72
---

Our community is largely volunteer-led. We depend on our members to get
involved in the running and decision making of NHS-R, so that it remains
a useful set of ever-growing resources to support and encourage our
membership.

In recognition of the significant contributions from members, the NHS-R
Community awards the honorary title of Fellow for a set period of 3
years.

Fellowships are a great way to advertise your contributions, show your
skill set and dedication to open source coding in healthcare, and
embellish your CV with evidence of your community spirit.

For details on how to nominate yourself or someone else for a
Fellowship, please visit the [NHSR-Way
book](https://nhsrway.nhsrcommunity.com/nhsr-fellows.html)

```{r}
#| label: fellowship-table
#| message: False
#| warning: False
#| echo: False
#| results: asis
fellows <- read.csv("Current_Fellows.csv", check.names = FALSE)
fellows |>
  dplyr::mutate("Valid From" = format(`Valid From`, format = "%b %Y")) |>
  dplyr::arrange(Name) |>
  gt::gt(id = "fellowship_table") |>
  gt::tab_header("List of current NHS-R Fellows") |>
  gt::tab_footnote("*Organisations listed are at the time of award") |>
  gt::opt_row_striping() |>
  gt::opt_css(
    "#fellowship_table .gt_footnotes,
    #fellowship_table .gt_heading,
    #fellowship_table .gt_col_heading,
    #fellowship_table .gt_table_body {
      color: unset;
      font-family: unset;
    }
    #fellowship_table .gt_footnotes,
    #fellowship_table .gt_col_heading {
      background-color: rgba(128, 128, 128, 0.15)
    }
    #fellowship_table .gt_heading {
      background-color: rgba(128, 128, 128, 0.2)
    }
    #fellowship_table .gt_table_body {
      background-color: unset;
    }"
  ) |>
  gt::as_raw_html(inline_css = TRUE)
```

If you have any questions about Fellowships, or would like to alter or
remove your details from the Fellowship list above, please email us at
[nhs.rcommunity\@nhs.net](mailto:nhs.rcommunity@nhs.net).

# *Thank you for your support!* 

