---
title: "Getting Started"
sidebar: false
page-layout: article
toc: false
title-block-banner: false
---

## Getting started with using open source tools and analysis

To read about why open source tools and analysis can help with our work and to get specific technical guidance on setting up those tools see our book [Statement on Tools](https://tools.nhsrcommunity.com/).
The technical appendices are written as instructions to get started but can also be shared with IT teams when getting things installed on networked computers and help to explain what is needed when asking for "R" on your computer.

We have very popular, volunteer led, workshops for [Introduction to R and RStudio](https://events.nhsrcommunity.com/) and whilst they are really popular it’s worth going on the waiting list as we sometimes offer spare places or notify people on the list of new courses. We also promote them through Slack and you are welcome to join <https://nhsrcommunity.slack.com/>

All the materials for our courses are free to use and reuse/change:

- [Introduction to R and RStudio](https://intro-r-rstudio.nhsrcommunity.com/)
- [Introduction to Quarto](https://intro-quarto.nhsrcommunity.com/)
- [Introduction to Git and GitHub](https://intro-git-github.nhsrcommunity.com/) using R 

And we have recordings in a YouTube Playlist called [Getting Started](https://www.youtube.com/watch?v=dS91HzZLD_c&list=PLXCrMzQaI6c1GC4P9zNw3N3dcfIUfvdEV&pp=iAQB).

## Asking for help

Key to learning is getting help and that can be from searches online but at some point you might need to get help from someone or a group of people.
Whether you post your question to someone directly, through a [Slack group](#contact) or on [Stackoverflow](https://stackoverflow.com/), you'll greatly increases the number and quality of replies if you can also share a **rep**roducible **ex**ample and there is a package that can help called [{reprex}](https://reprex.tidyverse.org/).

For a quick demonstration of using {reprex} as an RStudio add-in NHS-R Community have a short video with checked subtitles:

<iframe width="500" height="282" src="https://www.youtube.com/embed/iLfzNWh2dLI?si=rZwSEFIL0N7gBEJj" title="How to use the reprex R package to produce a reproducible example" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

If you prefer to use the command line or the R program (and not RStudio) go straight to [10:36 in the YouTube video](https://www.youtube.com/watch?v=iLfzNWh2dLI&t=636s).