---
title: "Community Office Hours"
format: html
---

## Disseminating knowledge, fostering community

Our community is composed of a large and growing group of enthusiasts for all things open source, health and collaboration. In this spirit, those who want to share their knowledge, support others and be part of the open source for health revolution, make themselves available for one on one 'office hours' on a rolling basis.  This time is bookable by community members (employees of the NHS, Local Authorities, Civil Service, Public Sector, Academia, Voluntary Sector or Charities) who are looking for some personalised help or learning on a specific aspect of open source coding.

All who participate in this scheme, whether as provider or as a recipient, must abide by our [code of conduct](CODE_OF_CONDUCT.md).

## INFO FOR RECIPIENTS{#recipients-info}
### What happens during office hours?

The help you could ask for from your provider might include pair coding, troubleshooting/debugging help, code walks, PR reviews, or simply discussion on a topic of interest. Please be aware, however, that your provider is not obliged to provide you any help outside of the booked time, whether in preparation for your meeting or in follow-up subsequently.

## I would like to speak to someone who knows about a particular subject

To view or search the list of available topics that our providers are happy to talk to you about, please [click here]().  You can browse or search for the topic you need help with, then select a provider whose availability works for your diary. 

Please DO NOT share code or data that are sensitive in nature or cannot be shared openly.

## INFO FOR PROVIDERS{#providers-info}
### Can you provide at least one hour per month to help a community member with a subject you love?

If you're interested in getting involved, it couldn't be easier! 

- In your Outlook calendar, click on 'Go to my booking page' (if you have access to multiple Outlook email accounts it may be easier to find this on the online version rather than the desktop version). 
- Follow the instructions to create a personal booking page. 
- Add a new meeting type called 'Community Office Hours'. Add a short sentence to describe these meetings, e.g. 'Time to support community members with open source learning'.  You can set the meeting length to 30 or 60 minutes, as you prefer (please note that, to be considered as evidence towards an application for a Community Fellowship you must make yourself available for a minimum of one hour per month). 
- Make sure you select to make the meetings public, and add the timing of these meetings that suit your work calendar. 

- Next, please complete [this form](). Each meeting needs to have a single 'theme' to make it simple for community members to find the help that they need, but you are free to add any number of subjects you're happy to help people with. The information on this form will be used to display your name, available subjects and booking link on our website.

## Frequently Asked Questions{#faq}

1. _How do I remove my name from the website list?_
Please email us at nhsrcommunity@nhs.net to let us know you'd like your booking info to be removed from the website. You can also go into your Outlook booking system and remove your availability.

2. _Somebody involved in this scheme has not been acting in accordance with the [code of conduct](CODE_OF_CONDUCT.md), what should I do?_
If you feel that a community member's behaviour has fallen below the standards we expect of our colleagues, please contact us a nhsrcommunity@nhs.net. We will do what we can to support you and prevent any further issues.

3. _Can office hours only cover a single subject?_
Of course not! Although recipients book time according to a single topic, you are free to discuss other topics as needed. However, if significant help is needed on a topic for which the provider is not confident, it is preferable to book time with a different provider who can help you with this topic.

4. _Can I send my provider my code beforehand?_
No, please do not send anything to your provider without their express permission. Remember, they are there to assist you within office hours only. Please respect their time by avoiding making requests for additional support.