---
title: "Webinars and Workshops"
format: html
---

Please note:

- Workshop attendance is restricted to UK employees of the NHS, public sector, civil service, voluntary sector, charities and academia, or who are retirees from any of these sectors. Please note you must sign up with a work email address to verify your credentials.
- Webinars are free to all to attend, and recordings are stored on our [YouTube Channel](https://www.youtube.com/@NHSRCommunity)

## September 2026

📆 10th **UK Address Matcher: High performance free address matching software with 
Tom Hepworth**:

_Address matching is a common challenge when working with messy, inconsistent, or incomplete address data. In this webinar, we’ll introduce uk_address_matcher, an open-source Python package for matching UK addresses to canonical address datasets such as Ordnance Survey AddressBase or OS NGD. We’ll demonstrate how the package can be used to run fast, transparent, and reproducible address matching workflows, including how to interpret match scores and choose appropriate thresholds. The session will also introduce ukam_os_builder, a companion package that helps users quickly access and prepare Ordnance Survey data under PSGA licensing, making it easier to get started with high-quality reference data. The webinar will include practical examples and discussion of how these tools can support robust analytical pipelines.
 
Links: 
https://github.com/moj-analytical-services/uk_address_matcher
https://github.com/moj-analytical-services/ukam_os_builder_

  + Webinar
  + 10:30 - 11:30 (BST)
  + 🔗 [Register to attend here](https://events.teams.microsoft.com/event/f4913672-0d1a-4509-b1b5-35ec2d96dc30@37c354b2-85b0-47f5-b222-07b48d774ee3)

📆 15th & 16th **Introduction to R and R Studio with Zoë Turner**:

_From ‘Hello World’ to producing a basic report.

This introduction takes you from no knowledge of R to teaching you the basics of the R studio environment, then loading in some data, some common data wrangling tasks, some charting and finishing with pulling it all together to produce a simple automated report.  

No previous knowledge is required. This workshop will utilise the cloud, with all datasets provided as part of the course material, so no specialist set up is required._

  + Workshop
  + 09:00 - 13:00 (BST)
  + 🔗 [Register to attend here](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=slTDN7CF9UeyIge0jXdO49xonCqYusFJh3y-kXmKM_1UM0pRTVZLVVJDSzVVWjFXRTI1VTFXVFVVSS4u)

📆 30th **Let’s Go!  An Introduction to Discrete Event Simulation and SimPy with Dr Daniel Chalk and Sammi Rosser**:

_Discrete Event Simulation (DES) is a simulation modelling technique that allows us to tackle queuing problems in health and social care.  These might include identifying delays in patient pathways and testing out the impact of reconfiguring processes and resources to try to reduce these delays.  DES projects in the HSMA Programme have led to significant impact nationally, including the construction of an £11.8 million new mental health ward in Devon to allow patients in crisis to be seen closer to home (https://hsma.co.uk/impact_posters/Out%20of%20Area%20Reduction%20in%20Mental%20Health.png), transformative improvements to urgent care delivery in London (https://hsma.co.uk/impact_posters/UTC%20Flow.png) and potential £1 million+ annual savings and improved patient outcomes for stroke patients in Kent (https://hsma.co.uk/impact_posters/Using%20Simulation%20to%20Improve%20Stroke%20Care%20and%20Reduce%20Costs.png).

The team behind the ARC South West Health Service Modelling Associates (HSMA) Programme invite you to a brand new standalone workshop “Let’s Go!  An Introduction to Discrete Event Simulation and SimPy”, designed for the NHS-OA community. 

In this workshop, participants will learn:
+ The principles of Discrete Event Simulation and the kinds of problems this modelling approach can be used to tackle
+ The importance of variability and stochasticity in simulation modelling
+ How to design reproducible stochastic models
+ How these models can be built in Python using the SimPy package, including how to use Python Generator Functions and how to structure code using Object Oriented Programming
+ How animated visualisations can be added to SimPy models using the vidigi package.

Whilst participants should have some prior coding experience, this does not need to be in Python.  We will assume no prior Python experience in this workshop.  Instead, participants will be introduced to the components of a SimPy model and shown the code that write these elements in Python.  Participants will also have a chance to adapt the code to write their own SimPy models.  In addition, no local software installation of Python is required - instead, we will use Google CoLab as a way of writing and running code, which requires only a free Google account.

As part of this workshop, we will be piloting new content and exercises written for the upcoming seventh round of the HSMA Programme, due to launch in early 2027.  For more information about HSMA, check out our website https://hsma.co.uk/.

The workshop be delivered online on Zoom with a lunch break and regular comfort breaks throughout the day. The workshop will be recorded._

  + Workshop - attendance is not restricted
  + 09:30 - 16:45 (BST)
  + 🔗 [Register to attend here](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=slTDN7CF9UeyIge0jXdO49xonCqYusFJh3y-kXmKM_1UOVNESlowTzRPU1RWTVJCTjNUSElSNTA3Ni4u)

## October 2026

📆 13th & 14th **Intermediate R with Zoë Turner**:

_This course is designed to follow on from the Introduction to R and R Studio course, noting that attendees should be familiar with the basics covered in the workshop. 

Please be advised that this session will go into more depth and complex wrangling tasks, explore how to use the NHS-R SPC plot the dots library and cover in very simple terms an understanding of some functional programming. This workshop will utilise the cloud, with all datasets provided as part of the course material, so no specialist set up is required._

  + Workshop
  + 09:00 - 13:00 (BST)
  + 🔗 [Register to attend here](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=slTDN7CF9UeyIge0jXdO49xonCqYusFJh3y-kXmKM_1UMzU2SDYwWEgxS0lIQjhSNjJKQk40R08zMi4u)
