---
sidebar: false
page-layout: article
toc: false
title-block-banner: true
---

The NHS-R Community started in 2018 to promote the use of R in the NHS and the community has grown rapidly ever since. 
It is a community that is broader than the NHS as members come from public sector organisations across the UK, including Local Authorities and Civil Service, as well as academics and voluntary sector people who have an interest in healthcare. 
Whilst R is a core language for support by the community, there is always support for data science tools more generally, particularly where they cross over with R.

:::{.callout-warning collapse=false appearance='default' icon=true}
## NHS-R Community and NHS Resolution
Occasionally NHS-R Community has been confused with an NHS organisation called [NHS Resolution](https://resolution.nhs.uk/) particularly as the email addresses share the first few letters.

As with any email sent from `nhs.net` to `nhs.net` [sensitive information is protected](https://digital.nhs.uk/services/nhsmail/guidance-for-sending-secure-email) but it's always advisable to share data using a password protected file just in case it goes to the wrong person.
:::


:::{.callout-warning collapse=false appearance='default' icon=true}
## WordPress site
This site is currently being moved from WordPress to Quarto. Once this is working and as compliant with accessibility as possible we will switch the nhsrcommunity url over.
:::

## Contact us

- **Email:** [nhs.rcommunity@nhs.net](mailto:nhs.rcommunity@nhs.net)

- **GitHub:** [@nhs-r-community](https://github.com/nhs-r-community)

- **LinkedIn:** [NHS-R Community](https://www.linkedin.com/in/nhs-r-community-2555a6282/)

- **Fosstodon (Mastodon):** [@NHSrCommunity@fosstodon.org](https://fosstodon.org/@NHSrCommunity)

- **Bluesky:** [nhsrcommunity.bsky.social](https://bsky.app/profile/nhsrcommunity.bsky.social)

For details on how NHS-R Community use social media can be found in the NHS-R Community book chapter [Community Handbook](https://nhsrway.nhsrcommunity.com/community-handbook.html#social-media).

## Special thanks

To the creators of Quarto and to those who publish their code to share their knowledge particularly the website [Real World Data Science](https://realworlddatascience.net/) and Silvia Canelón's [personal site](https://silviacanelon.com/).

Both were instrumental in building this site as they share the code from their website but have also contributed to the NHS-R Community Conferences:

* Brian Tarran opened the NHS-R Community Conference in 2023 with his talk [Forging community links: NHS-R, the Royal Statistical Society and Real World Data Science](https://www.youtube.com/watch?v=8jcPwD8x8WE&t=18953s).

* Silvia Canelón ran a two-part Xaringan (including CSS) workshop at the 2020 NHS-R Conference - [Part 1](https://www.youtube.com/watch?v=M3skTMQbCD0) and [Part 2](https://youtu.be/cAtpZxW4bTI?si=NXNA_TeWLlUtovBj). 
And as part of this workshop Silvia kindly created [{NHSRthemes}](https://github.com/nhs-r-community/NHSRtheme) which contains the code for the NHS Branding colours used in this site.