---
title: "AphA April 2023 Blog"
date: "25 April 2023"
date-modified: "27 July 2024"
categories:
  - NHSR
author: Zoë Turner
subtitle: >
---

First published for the [AphA](https://www.aphanalysts.org/) April 2023 newsletter:

This is a new look for the updates from NHS-R Community as we’ve had a few changes recently in the NHS-R Community support and this is a great opportunity for us to share what we’ve been working on and our plans for the future – which you can be a part of if you haven’t already found us!

The NHS-R Community started out with funding but that was for a fixed period which came to an end last year. Thankfully the community has grown to such an extent that the value of what we can achieve was recognised by the Strategy Unit, part of NHS Midlands and Lancashire Commissioning Support Unit, and two roles were created with NHS-R Community support in the job description. Those roles were filled by Chris Beeley and me, Zoë Turner, as Data Scientists.

Our roles are not solely supporting NHS-R Community, but like we did when we worked in Nottinghamshire Healthcare NHS Foundation Trust, our dedication to the NHS-R Community, supporting data science learning and being open pervade all that we do. Chris is leading the newly formed Data Science Team in the Strategy Unit which is a privilege to be a part of. I worked with Chris, as many people know, in the Clinical Development Unit in Nottinghamshire, using R and publishing our code and methodology in the open. I found publishing things incredibly difficult at first, not because it’s technically hard to do; it takes time to learn but not impossible. It was more the culture of sharing openly was new and uncomfortable. I had a lot of anxiety about what I could publish and if I’d make mistakes but, crucially, when I made mistakes, I was part of a supportive team which helped me make corrections and gave me the encouragement to keep practising.

And it’s with this experience that I’ll be concentrating on supporting analysts and data scientists across health and social care to learn and practice new skills in data science. I’ll be developing and delivering training as part of my role in the Strategy Unit on a consultancy basis but all materials will be published through the [NHS-R Community GitHub](https://github.com/nhs-r-community) repository under an open licence. We regularly have volunteers from the community deliver the free Introduction to R and R Studio training [Events](https://nhsrcommunity.com/events/) and I hope to extend this in the coming year to include using Git with RStudio for version control and open publishing of code.

NHS-R Community will also have a presence at the first national analytics conference for health and social care [HACA2023](https://uobevents.eventsair.com/haca-2023/) at Birmingham Medical School on 11-12 July 2023 which has had a huge number of submitted abstracts to it so do sign up now!

And as we have done since 2018, we’ll be putting on the NHS-R Community (hybrid) Conference this year with talks planned for 17-18 October 2023 at Edgbaston Cricket Ground in Birmingham. Abstracts will be out for contributing to very soon and we’ll also be looking for people to run workshops which will planned over a week with dates to be confirmed soon. All workshops, like last year, will be virtual so people can join in from across the UK. After the success of NHS-R Community’s conference last year, we’ll be including talks and workshops for Python.

We have grown so much as a community with so much material I’ll be spending some of my time to helping curate. We have a website [NHS-R Community](https://nhsrcommunity.com/), a [GitHub repository](https://github.com/nhs-r-community), a [YouTube channel](https://www.youtube.com/c/NHSRCommunity), write [blogs](https://nhsrcommunity.com/blogs/blogs/) and create regular [Podcasts](https://soundcloud.com/nhs-r-community) but we are mindful it can be overwhelming knowing where to start with finding the NHS-R Community and perhaps also to contributing to it …

… so I will end with the one link you need to find the people who make up the community which is the [Slack workspace](https://nhsrcommunity.slack.com/). It’s open to anyone who is interested in R (and other languages) and healthcare. We post all our updates and news regularly in this space and I hope to see you there sometime but, if you want to contact us via email, we can be found at [nhs.rcommunity\@nhs.net](mailto:nhs.rcommunity@nhs.net).

This blog is also available in its original quarto script on [GitHub](https://github.com/nhs-r-community/NHSRblogs/tree/main/20230425-apha-april), comments on this blog can be made here or as a [GitHub issue](https://github.com/nhs-r-community/NHSRblogs/issues).
