---
title: "AphA June Blog"
date: "18 July 2023"
date-modified: "27 July 2024"
categories:
  - NHSR
author: Zoë Turner
subtitle: >
---

First published for the AphA June 2023 newsletter:

# **Conferences update**

The news update on the upcoming conferences that NHS-R Community is involved with:

## **HACA23 11-12 July**

Just a few weeks left until the [HACA23](https://uobevents.eventsair.com/haca-2023/)! Tickets are free and you can still sign up for virtual tickets. Follow the Twitter account [HACA_Conf](https://twitter.com/HACA_Conf) for more information.

## **NHSR Community Conference 17-18 October**

Abstracts for the NHS-R Conference was extended to 23rd June and, by the time this is published, will have passed. Now it’s time to watch this space for information on how to get tickets and notices on who will be speaking at both the virtual and live days!

# **Communication is hard!**

In the NHS-R Slack group we had a message about how the notices about the conference had not filtered through to people. We are still active on social media, but many people have moved away from social media, particularly Twitter, and not everyone has access to Slack or checks it regularly. These are very valid points and it’s worth recognising how hard communication can be and recognise that communication is a speciality in itself. Whilst we’ve possibly done well with communicating to those who already know about NHS-R we need to keep working at promoting our work more. We’d welcome help and advice in this area!

## **New Open Analytics Resources book!**

This book is new and not new at the same time! AphA had originally commissioned a [Google document](https://docs.google.com/document/d/15unzokDyUQR_YLWFqBwVvds3C6B69sZn_3OQro9gB3E/edit#) released under a CC-BY-SA licence in 2020. Because this is an [open licence](https://nhs-r-community.github.io/statements-on-tools/open-code.html#licenceslicenses) I’d copied this originally to my own GitHub to tidy up some of the dead links and to add more. As with many personal projects, I’d left this for quite a long time as I worked on other things and then, more recently, decided it would be useful to move this book to the new Quarto format and update the links. Lots of those links had disappeared, particularly relating to Covid, and proves just how books/documents like this are living documents. Following a [talk](https://nhs-r-community.github.io/NHSRpresentations/20230613-government-toolshed/NHSRtoolshed.html#/title-slide) I gave to the Government Data Science Community at their [Toolshed meetup](https://www.eventbrite.co.uk/e/government-data-science-community-meet-up-the-data-science-toolshed-tickets-578774920367) I took my own suggestion and passed the book over to NHS-R Community which is where you can now find it! https://nhs-r-community.github.io/open-analytics-resources/. Comments, corrections and thoughts on the book can be made through issues and pull requests directly to the repository.

## **Contributing to GitHub requires knowledge of Git**

Although the NHS-R Community work is on GitHub there are a couple of issues people can have with that, firstly contributing can be difficult if you don’t know how to use GitHub/Git. As part of some training required for the Midland Decision Support Network I’ve been writing training slides for an [Introduction to Git/GitHub](https://github.com/nhs-r-community/intro-git-github#introduction-to-git-and-github) which differs substantially from many training materials for Git as it relies much more on R and R Studio rather than the command line. The course is still a work in progress but will be finished shortly – I hope – so analysts in the Midlands area can attend free courses as part of MDSN and I’ll be doing a couple for the NHS-R Community.

## **Access to GitHub**

The second issue is just any access to GitHub, particularly published things like books and these training slides as not every organisation allows access to the `github.io` url. We’ve got around this for some things by using the Netlify publishing which has a free plan up to a certain amount of usage, however, this was through my own personal account. That’s not ideal and also not a solution as some really secure IT have blocked both publishing sites. Consequently, we’ve started looking into the possibility of using the `nhsrcommunity.com` url which is where we currently publish the main WordPress site.

## **Why so many books?**

The reason why having books is so nice is that I now only need to write things out in one place and can refer to them repeatedly. Quarto makes this so simple too as it can be used by both R and Python users. Whereas the previous version (still available and not going anywhere) RMarkdown was well loved by R users, it did require a bit more work to publish things like books and website, using other packages and requiring many specific files to work correctly. Moving to Quarto was more straight forward than I thought and I did use the [R for Data Science (2nd Edition) Unofficial Solutions book](https://github.com/nhs-r-community/r4ds-ed2-exercise-solutions), set up by my colleague Tom Jemmett for our book club, as a guide.

## **Book club!**

The book club in NHSR started many years ago when someone asked in the Slack group if anyone else would be interested in reading “The Art of Statistics” by David Spiegelhalter with them. There was a lot of interested people and it was one of the most popular [book clubs](https://github.com/nhs-r-community/book_group) we’ve had! Since then we’ve tackles more statistics books like “The Book of Why” by Judea Pearl (I’m not going to lie, that was a tough one!), “Invisible Women” by Caroline Criado Perez (that was interesting, particularly when we looked up some of the references which didn’t really satisfy our analyst curiosity) and “R for Data Science (1st Edition)” by Hadley Wickham and Garret Grolemund. We started the Unofficial solutions book, inspired by the work of [Jeffrey B Arnold](https://jrnold.github.io/r4ds-exercise-solutions/).

Originally I’d thought about updating his book as the numbers had got out of line with the text – being online R4DS had had revisions, however, with the second edition coming out we decided to work through this together at NHS-R https://nhs-r-community.github.io/r4ds-ed2-exercise-solutions/ Book group meets every two weeks (which has changed due to holidays) 3-4pm GMT/BST (we do have some people join us internationally) and details are shared in the Slack group.

## **Join the Slack groups**

Now that I have one link to the Slack groups check out our book for links https://nhs-r-community.github.io/open-analytics-resources/forum-groups.html#slack!

Contact NHS-R Community via email at [nhs.rcommunity\@nhs.net](mailto:nhs.rcommunity@nhs.net)
