---
title: "Hexitime is shortlisted as a finalist for the HSJ Partnership Awards 2021"
date: "14 December 2020"
date-modified: "12 July 2024"
categories:
  - NHS-R
author: Beth Taylor
subtitle: >
---

Hexitime has been shortlisted for Best Not for Profit Working in Partnership with the NHS at the HSJ Partnership Awards 2021. This recognises outstanding dedication to improving healthcare and enabling effective collaboration across the NHS.

Following the most testing period for the healthcare sector in recent history, this year’s awards reinstate the essential role of private and third sector organisations in strengthening the healthcare system. Being shortlisted for a Partnership Award has given our team the confidence in our worthwhile project and has ensured that our time saving project is nationally recognised, learned from and up scaled.

The judging panel comprised a diverse range of highly regarded figures across the NHS and wider healthcare sector. To be shortlisted as a finalist for these awards, despite tough competition from a pool of brilliant applications, is a mark of real achievement for the NHS-R Community, Hexitime and their partners KSSAHSN and Walsall Together. That Hexitime has been selected based on their diligence, ambition, and the positive impact that the project has had on both practitioners and patients within the health care industry.

**In the last year, hundreds of hours have been exchanged across the country, bringing skills to where they are needed when they are needed and hence adding value to staff, organisation and networks. The partnership with the NHS-R Community, KSS AHSN and Walsall Together has allowed the platform to be provided free to use for all staff in health and social care, enabling them to collaborate across organisational and professional boundaries**.

Hexitime Co-founders Dr. Hesham Abdalla and John Lodge commented:

> *We are delighted to have been shortlisted for Best Not for Profit working in partnership with the NHS, recognising the collaborative efforts and dedication of our team/s to successfully implement Hexitime. We are committed to delivering improved outcomes for patients, and to be chosen among the other incredible nominees is a wonderful achievement. This nomination has been a tremendous boost to both to our team and our NHS partners and I am sure it will bolster our continued efforts to improve health and care.*

NHS-R founder Prof. Mohammed Mohammed commented:

> *Hexitime enables us to mobilise, visualise and marvel at our amazing NHS-R community that is bringing 21st century open-source data science solutions to the NHS.*

HSJ editor Alastair McLellan comments:

> *We would like to congratulate Hexitime on being nominated in the category of Best Not for Profit working in partnership with the NHS ahead of HSJ Partnership Awards 2021. We are looking forward to welcoming them to the ceremony in June, to join us in recognising the very best collaborations and innovations in the healthcare sector. This year’s finalists are of an outstanding calibre and all of them are exceptionally dedicated to enhancing healthcare across the UK.*

The winners will be selected following a rigorous, judging stage ahead of the HSJ Partnership Awards 2021 awards ceremony. The awards evening is expected to be attended by leaders and professionals from both the NHS and private sector as well as figures from non-clinical backgrounds to celebrate innovation and collaboration in healthcare.
