---
title: "July Blog"
date: "19 July 2023"
date-modified: "27 July 2024"
categories:
  - NHS-R
author: Zoë Turner
subtitle: >
---

# **Government Data Science Toolshed Meetup and DataConnect23**

Back in June I attended a [Government Data Science (GDS) Toolshed](https://www.eventbrite.com/e/government-data-science-community-meet-up-the-data-science-toolshed-tickets-578774920367) meetup for Public Sector and cross Government, the name coming from the idea that we have tools that we've built in our teams that we'd like to share. Matt Dray skilfully found a [metaphor](https://matt-dray.github.io/government-toolshed/#/a-metaphor) (and corresponding pictures) to explain this idea and I got the chance to showcase NHS-R GitHub repository and invite people to join us in our Toolshed!

Inspired by this way of thinking about the NHS-R Community GitHub I'll be doing a workshop repeating this message for the upcoming [DataConnect23](https://www.gov.uk/government/news/dataconnect23-is-on-its-way) which is open to Public Sector and Cross Government. My hope is that I can get the message out to as many people as I can about how this is a place where you can get involved as much, or as little, as you like. We have a toolshed where people can practice, play and use tools we've created.

# **Catch up questions**

The GDS Toolshed meetup was incredibly popular and I was able to answer a few questions at the time but there were still a few to get around to and I will use this blog to answer them.

## **How do you get support and recognition for your work building the community?**

I can't clarify if this was a particularly directed question for me as an individual or more about anyone wishing to get involved with NHS-R (or any community) but I'll assume it was the latter as that covers me too!

Getting time allocated to working on what are seemingly side projects, or getting recognition for your efforts can definitely feel strange and I've never formally requested or put forward anything like a business case to do this. I've been lucky to have a manager who could see the value in the work that NHS-R Community do and how that will consequently benefit my work as well as ultimately contribute to making the NHS better.

Talking about the NHS-R Github like a Toolshed was a bit of an epiphany for me because the things we make are sometimes highly polished things (the packages {NHSRdatasets} and {NHSRplotthedots} both on CRAN are very professional projects) whilst many other repositories are just set up or very much work in progress. Sometimes things get started and then abandoned and that's ok as we can archive things in GitHub so they are not lost but are tidied away!

I, and others, have been able to do things which were not directly related to our work, like teaching and creating websites/books using R, but I've certainly gone on to use those skills in my work and I'm sure others have done too. Quantifying and justifying why this is useful will take time in itself and the question is, is that useful when I could be learning through doing?

# **How does NHS-R go out to trusts/community to uncover tools?**

Great question and it has to be simply, the NHS-R Community lets us know.

For the tools that I showed in the talk, where people had passed them to NHS-R Community, those individuals had prompted the move and it was very welcomed. We've had a few things over the years created on the GitHub repository directly but recently we've had projects passed to us. I guess the reason for this is around centralisation, having projects located in the NHS-R Community itself helps raise the profile, making them more discoverable and by giving the repositories to NHS-R people can continue to be involved, take full credit and maybe, hopefully, take away some of the barriers to inviting contributions.

In finding tools, I'm a bit like a magpie and collect links all the time and I don't think I'm alone in that as we had a few attempts on getting things coordinated with “finds” as we've come to refer to them. We now have a very informal process where we, as a community, share anything we think is fun or useful (or both!) in the #finds channel in [Slack](https://nhsrcommunity.slack.com/) and then promote that in blogs here and talk about them on the NHS-R [Newscast](https://soundcloud.com/nhs-r-community).

I've also built upon some open source work previously started by [AphA Analysts](https://www.aphanalysts.org/), for a book called [Open Analytics Resources](https://resources.nhsrcommunity.com/) where I keep a lot of the links I've found and people have shared on the Slack. This book is slightly more curated towards NHS analyst needs and features NHS-R, NHS and Government resources and if you are wanting almost a “definitive guide to resources” then a better place to go, as well as contribute to, is the [Big Book of R](https://www.bigbookofr.com/) which has thousands of resources!

## **What lessons did you learn in growing a community?**

For me it's the realisation that work is fun and rewarding because of people and their kindness. I wouldn't have known that I needed something like the NHS-R Community before it existed. In fact, I only came to know about it because a colleague mentioned there were some free R courses by NHS-R back in 2018. That could have been the end of my involvement but the work of passionate people to get the community up and running meant more opportunities were created where I could get involved and no one said no I couldn't.

So frequently we have things “dictated” to us in our work but with communities, it's more equal. Yes, some people will know more things but if you can work combine your skills and experiences we can make an even greater impact.

## **Do you think it was hindrance to name it NHS-R? Or did that help build the community at the beginning?**

Yes, it probably helped to rapidly build a trusted “brand” but now we are conscious that the name “NHS” and “R” can feel exclusionary. Whilst there have never been strict boundaries to who can get involved we still need to work hard to tell people we are more than NHS and interested in more than R. Perhaps one day we won't have to do this, maybe we'll need a rebrand, but whatever the solution there is nothing like word of mouth to get the message out.

How we fit in with other communities is difficult too, not because we don't get on but because we want to be inclusive and so overlap but we don't want to take over. There are many people who you'll find in all three communities: NHS-R, NHS Pycom and Government Data Science (me for example) who get something different from each group. I personally have all three Slack channels open and keep an eye on all the conversations because I'm curious but I'm most active in NHS-R and Government Data Science Slack groups because that's where I'm most confident in my own knowledge of NHS and R.

# **NHS-R Community conference update – questions and social media**

We have had our highest ever submission of abstracts this year! Consequently, as we hope to give as many people as possible a presentation slot we've decided to try out having everyone at the next NHS-R Community conference ask questions virtually. Our intention is to give equal opportunity to virtual attenders to get involved in what will be a streamed event in terms of the hybrid days on 17-18 October.

This is just a trial but if you have any suggestions or advice for us as we continue planning this event, please do get in touch!

## **Join the Slack groups**

Details are in the [Open Analytics Resources](https://resources.nhsrcommunity.com/forum-groups.html#slack) and feel free to contact NHS-R Community via email at [nhs.rcommunity\@nhs.net](mailto:nhs.rcommunity@nhs.net)
