---
title: "Local Public Health joins the paRty"
date: "22 November 2018"
date-modified: "24 March 2024"
categories:
  - Reflections
  - Public Health
author: Andy Evans
subtitle: >
  "Setting up an R group for Publich Health Intelligence"
---

Having recently attended an R meetup in Birmingham, hearing of various user groups and hackathons that take place around certain technologies, I was getting a feeling that there was an increasing desire in the public health community to learn more about R and modern data science tools and techniques. I wondered whether there would be interest in a data science and R user group for the West Midlands public health intelligence community. I thought I’d raise the idea at the West Midlands Public Health Intelligence Group (WMPHIG) when I attended the quarterly meeting, but another attendee beat me to it and doing so confirmed there was some interest. I volunteered to arrange the first user group and Public Health England (PHE) kindly offered assistance.

Between us we setup a date and venue for the first meeting at the PHE offices in Birmingham and I was pleased to hear from Nicola at PHE that “…Tickets are selling like hotcakes! “

Not knowing exactly how the group would best work, we suggested a loose structure for the meeting with the following discussion points:

- How this group should work  
- Assess current levels of knowledge/experience  
- R training requirements  
- R learning methods  
- Public health R use examples (including Fingertips R) & wider use examples  
- What could be done with R / What else do people want to do with R  
- Challenges and issues people have experienced/are experiencing  
- Possible joint projects that might benefit all members  

We ended up staying reasonably on topic, but there was plenty of useful and engaging discussion around the topics of data science and R. The was a nice mix of novice and more advanced R users (though no one admitted to being an expert 😉 ) in the group.  Many of those who were more advanced had fairly recently been novice users. Whilst the more advanced users were able to share their experiences of their learning journeys, others were able to contribute on how we might develop use of data science and R in Public Health Intelligence. I was also impressed with some of the examples of R use that were shared with the group by analysts who have only been using it for a relatively short time. A key point shared was though R may seem a bit daunting at first, its worth jumping in and getting your analytical hands dirty!

A number of attendees had also managed to attend the NHS-R Community Conference and shared positive experiences of the day and the knowledge they’d picked up.

Everyone appeared to agree that R and other modern data science tools/methods can offer a lot to public health intelligence.  There also appeared to be a desire to work together and help each other out on this learning journey. With that spirit in mind, we have agreed to share code and other useful information on K-Hub ([https://khub.net/](https://khub.net/)) and another meeting is going to be arranged for next quarter.

Thanks to all that attended and contributed and to PHE for helping with the organisation.

This blog was written by Andy Evans, Senior Officer at Birmingham City Council.