---
title: "Thoughts on the NHS-R conference"
date: "15 November 2018"
date-modified: "23 March 2024"
categories:
  - Conference
author: John MacKintosh
subtitle: >
  "Reflections on the 2018 Conference"
---

It's been a few weeks since the first NHS-R conference was held in Birmingham.

I co-presented a couple of workshops with Neil Pettinger on visualising patient flow, covering the following

- importing from Excel (and connecting to SQL Server)
- dplyr
- ggplot2 & plotly
- gifski for basic animation
- automating reports with officer
- gganimate demo
- tidy evaluation via a custom plot function
- alternative flow plots with ggalluvial
- a simple Shiny app
- Code, data and templates for the workshop are available here.

I hope those who attended found it useful.

The event itself was a huge success. I'd have loved to have been able to see all the sessions that were taking place.

There were a series of lightning talks – there are Trusts using R for machine learning and classification, and others using it for predicting admissions [Chris Beeley](https://chrisbeeley.net/) presented on the use of Shiny, while Jacob Anhøj led a session on SPC using his qicharts2 package. It was a huge honour to meet Jacob, I've used his package almost since inception, and I know how much effort has gone into the rigorous analysis the package provides.

I was also very pleased to meet Chris (Beeley), [Gary Hutson](http://hutsons-hacks.info/), Ed Watkinson, Zoë (who masquerades on Twitter as Applied Information Nottingham) and Garry Fothergill face to face, and to see Val Perigo, Paul Stroner and Professor Mohammed Mohammed again. I also want to say thank you to Shahima who helped me revise my incredibly shoddy attempt at a bio, and for organising the event.

From my point of view, the workshop was enjoyable to deliver. There were a couple of technical glitches ( I couldn't share my laptop screen, so had to project it and then fly blind , which led to me spending more time facing the screen than the audience, which was not ideal), but even with that, we got through the material and it all worked within the allotted time.

It was great to be in a room full of analysts passionate about R and the NHS. Neil mentioned ‘community' in his blog post, and it is true. There was a great vibe, as I'd expect to be honest. I've never been one for being part of a gang but anyone into R in the NHS is instinctively all right by me 🙂 I'm pretty sure there was enough brain power in that room to tackle any analytical challenge that could get thrown at the NHS. The challenge is in harnessing that power , promoting R as the incredible tool that it is, and enabling us to work collaboratively rather than in silos. If only there was an R package for that..

This blog was written by John MacKintosh,  Data Manager at NHS Highland and was originally posted on John Mackintosh's own blog [Data by John](https://www.johnmackintosh.com/blog/2018-10-31-thoughts-on-the-nhs-r-conference/)
