---
title: "We need you: share your COVID-19 work on NHSE/I’s regular mini-huddle series"
date: "21 May 2020"
date-modified: "11 July 2024"
categories:
  - Covid-19
author: Sophie Hodges
subtitle: >
---

COVID-19 has placed the value of data and analytics at the fore. This has meant an unprecedented focus on the work of health and care analysts, but also huge demand for local analytical services. The need to share and share alike is paramount.  To support this, NHSE/I are holding a series of huddles and mini-huddles to allow analysts to share their COVID-19 work with a wider community.

:::{.callout-warning collapse=false appearance='default' icon=true}
## FutureNHS
The link to the FutureNHS recordings no longer works. 

This is a platform that anyone can join but some workspaces are restricted in access <https://future.nhs.uk/> and the DataAnalyticsCovid19 workspace redirects to AnalystX which may be open to general registration.
:::


Weekly huddles showcase work on a specific topic, and the back catalogue of recordings can be found [on FutureNHS](https://future.nhs.uk/DataAnalyticsCovid19/view?objectID=18976912). The mini-huddles are a spin off series where speakers get into the detail behind a single topic, like geo-mapping or a dashboard. The team curating these huddles are keen to have a mini-huddle on COVID-19 analysis in R. **If you are interested in sharing your analysis relating to COVID-19 using R, please get in touch with Sophie Hodges** via email [sophie.hodges5\@nhs.net](mailto:sophie.hodges5@nhs.net)

 If you haven’t already, please sign up to the COVID-19 data and analytics workspace [here](https://future.nhs.uk/DataAnalyticsCovid19/grouphome). The community is currently 6500-strong with members across the NHS, public health, local authorities, charities and commercial organisations. Mini-huddles usually draw an audience between 30 and 80 attendees so it’s a great opportunity to share your work, discuss findings and network with others working on similar issues.

Please get in touch if this sounds of interest. And a huge thank you from NHSE/I. The work being done by the analytical community is a key plank of the COVID-19 effort.

Sophie Hodges, NHS England and NHS Improvement - Project Manager – Graduate Analyst