---
title: "What is a “proper” data scientist anyway?"
date: "8 January 2024"
date-modified: "27 July 2024"
categories:
  - NHS-R
author: Chris Beeley
subtitle: >
---

I’ve talked to a lot of people over the years about whether they’re a “proper” data scientist. When I started writing code to analyse data there were no data scientists in the NHS, or none that I knew at least. In 2012 data science was called [The sexiest job of the 21st Century](https://hbr.org/2012/10/data-scientist-the-sexiest-job-of-the-21st-century) and still I couldn’t see it anywhere in the NHS. I started calling myself a data scientist around 2017, and I started calling the people in my team data scientists too. In my book, if you’re trying to get better at data science, that means if you’re trying to know more about computing than a statistician, and more about statistics than a software engineer, you’re a data scientist, however great or terrible you are at it. I have a long running joke that I have a special sword in my office that I can use to “Knight” people and make them Proper Data Scientists.

I had an experience that made me think about this long running issue recently. My team is working on quite a large complicated model that’s being rolled out at the moment. There was a big workshop coming up and we needed to get it looking the part. To meet the deadline I put everything else down for 1-2 weeks and wrote some code with the rest of the team. In my current role I basically never write any code which feels strange after 10 years of doing little else but that’s another blog post for another day. I was a little surprised, or I suppose not all that surprised, to find that I was a bit intimidated. I was sending pull requests for review to the person who wrote the code originally and I was a bit worried about what they’d think of me. This person is a helpful, friendly person I’ve known for a long time, never passes judgement on those who are still learning, they are line managed by me, and they know full well I haven’t written any code for a year (so might be sympathetic) but I was still worried about what they would think of my pull request.

And quite honestly the other part of my job, the what the heck else I do all day as a data scientist would doesn’t write code, I don’t really feel like I know what I’m doing there either for a good chunk of the time. I came to my new role to stretch and challenge myself and it’s certainly working but I’m often finding myself doing something I’ve never done before (leading a conference) or something I’ve done lots of times but am just not particularly good at (faffing around with budgets and timesheets and all the other paperwork stuff). The point of this blog post is to say that in my experience that fear never really goes away. My advice would be to stretch and challenge yourself, sure, but don’t question whether you’re a “proper” anything. I’m as good at writing code as I’m ever going to be now I’m doing other stuff with my time, and I’ve really just started the long journey to growing and improving as a data science team manager. And that’s OK. And if you’re reading this and you’re trying to be a better data scientist, however great or terrible you are at it, you’re a data scientist. And I’ll bring my special sword to knight you as a proper data scientist to the next NHS-R conference to prove it.

Chris Beeley, Head of Data Science, Strategy Unit, MLCSU
