---
date: "2024-02-16T09:00:00+00:00"
title: "NHS-R Constitution"
---

# Sponsorship policy

## Purpose of the Policy

In order to enhance, vary or reduce the cost of NHS-R Community activities, the NHS-R Community may enter into sponsorship agreement(s). 
These may involve the NHS-R Community granting sponsorship to a third party or parties in the form of some benefit, or the NHS-R Community receiving sponsorship in the form of some benefit from a third party, with the intention in all cases being to support and/or promote the NHS-R Community’s activities.

When granting sponsorship, the NHS-R Community must also consider the provisions relating to granting financial assistance content in the relevant legislation.

Sponsorship can be advantageous for all parties; however, the NHS-R Community must ensure all sponsorship agreements do not compromise or question the integrity and independence of the NHS-R Community’s operations.

## Objectives and Coverage of the Policy

The Sponsorship Policy outlines the principles and procedures for accepting and granting of sponsorship proposals.
The Policy is concerned with:

Assessing risk and managing potential conflicts of interest;

Accountability and transparency of decision making;

Financial management and benefits.

## What is sponsorship?

Sponsorship can be defined as “a business relationship of mutual benefit involving the transference of funds, resources or services from the sponsor to the sponsored party in return for an association and a set of rights which are to the mutual satisfaction of both parties”.
Sponsorship is not philanthropic and a sponsor will expect to receive a reciprocal benefit beyond a modest acknowledgement.

Sponsorship is a significant business activity and companies seek sponsorship opportunities for a variety of legitimate business reasons including:

to raise the company’s image and public profile;

to improve public/community relations and instil goodwill;

to show creativity and public spirit;

to generate public exposure and media coverage;

to differentiate the company from its competitors;

to increase profits/market share.

The connection of a company’s name with the NHS-R Community’s events or activities can be particularly attractive in terms of the opportunities for media coverage and as a display of public spirit. 
In some cases, sponsors’ motives, or the benefits the sponsor anticipates, may be less apparent.
Careful consideration should always be given to understanding what a sponsor might gain from the arrangement.

The NHS-R Community encourages the involvement of the private and voluntary sectors in the sponsorship of NHS-R Community activities wherever appropriate. 
Sponsorship can help exploit the commercial potential of the NHS-R Community’s non-tangible assets, allowing more productive use of existing resources and, potentially, reducing the cost of our activities.

Sponsorship should not be confused with advertising which can be defined as “any paid form of non-personal presentation and promotion of ideas, goods or services by an identified NHS-R Community”.

# Principles

All sponsorship agreements will be in the form of a written agreement and comply with principles and procedures outlined in this policy.

The Council must consider whether the granting of sponsorship may require consideration of relevant legislation as it may be deemed as ‘financial assistance’.

Sponsorship agreements must include a statement that that the NHS-R Community’s functions will continue to be carried out fully and impartially, notwithstanding the existence of a sponsorship arrangement.

There should be no real or apparent conflict between the objectives and mission of the NHS-R Community and those of the sponsor.

The agreement will include a statement to the effect that any attempted influence of the NHS-R Community’s regulatory functions will result in an automatic review and/or termination of the sponsorship agreement.

Any consideration given to the establishment of sponsorship agreements shall have regard to the following principles:

not perceived to influence or hinder how the NHS-R Community operates;

do not impose or imply conditions that would limit or appear to limit the NHS-R Community’s ability to carry out its functions fully or impartially;

the reputation and credibility of the NHS-R Community is not damaged by making agreements with unsuitable third parties;

the form of sponsorship is consistent with the stated objectives of the NHS-R Community which includes the NHS-R Community’s image;

agreements can be terminated if conditions of this policy are not met;

agreements are formed with regard to public accountability and transparency with clear statements of objectives and benefits achieved.

# Risk Assessment

Each sponsorship proposal must be subject to a risk assessment. 
This includes assessing:

ensuring that the sponsorship benefits for the third party do not outweigh the level of sponsorship;

ensuring that the type or form of sponsorship is not inconsistent with the objectives or needs of the NHS-R Community (e.g. accepting free products simply because they are free but not of any perceivable benefit to the NHS-R Community);

ensuring that any sponsorship proposal does not anticipate explicit endorsement of the sponsor or sponsor’s products, as this form of proposal is not acceptable to the NHS-R Community;

ensuring no conflict of interest arises from the sponsorship;

sponsorship that does not eventuate the capacity of the NHS-R Community to provide adequate resources and facilities to meet the terms of the proposed agreement.

If the assessment concludes the risks are unacceptably high or the NHS-R Community is receiving minimal value from the proposal, the NHS-R Community should discontinue consideration of the proposal at this stage.

The NHS-R Community should not accept sponsorship from parties’ subject to or likely to be subject to their regulation or inspection.

Every sponsorship proposal will be assessed against the possibility of a conflict of interest.

NHS-R Community Granting Sponsorship

The NHS-R Community can receive requests to ‘sponsor’ activities of an external party e.g. provide funding or resourcing of activities. 
In most cases, ‘sponsorship’ is actually a request for financial assistance or support. 
These requests must be assessed in accordance with this Policy.

# Unsuitable Activities for Sponsorship

Without any limitation on the NHS-R Community’s ability to exercise its discretion, the NHS-R Community does not consider the following companies, partnerships, NHS-R Community’s or individuals as suitable for entering into sponsorship agreements with:

Those involved in the manufacture, distribution and wholesaling of tobacco related products, pornography and addictive drugs;

Those found guilty of illegal or improper conduct by any other legal authority;

Those which are involved in political fields [e.g. political parties];

Those whose services or products are considered to be injurious to health, or are seen to be in conflict with the NHS-R Community’s policies and responsibilities to its members.

# Acceptable Types of Sponsorship

The NHS-R Community can recognise its sponsors in a number of ways.
The extent of such recognition is to be determined in relation to the level and nature of the sponsorship; and is subject to written agreement specifying the benefits and costs.

Sponsorship recognition should be tasteful and discrete and must not create situations of potential embarrassment or criticism of the NHS-R Community.
Such forms of recognition can include, but are not limited to:

appropriate signage;

media release acknowledging the role and contribution of the sponsor invitations to selected NHS-R Community functions, which may include hospitality, preferential seating, award presentation;

inclusion of sponsor’s name and logo on NHS-R Community publications and other external publications;

naming rights for an event, for the term of the sponsorship;

an award or trophy struck in the sponsor’s name and publicly presented;

merchandising of goods at selected NHS-R Community events e.g. Regional Branch meetings;

an opportunity for the sponsor’s name and/or logo to be promoted through appropriate general advertising by the NHS-R Community;

# Agreements

The NHS-R Community’s approved form of Sponsorship Agreement shall be used in all circumstances wherever possible. 
However, it is acknowledged there may be circumstances in which the sponsor may require its own form of agreement to be used. 
Notwithstanding this, every sponsorship agreement will require a written agreement incorporating conditions of contract which clearly set out:

the benefits, including economic benefits available to the Council and the sponsor and the nature of the benefits e.g. naming rights;

any personal benefits available to the sponsor’s employees and their relatives;

the form or forms of sponsorship acknowledgement which will be available;

the scope of uses which the sponsor can make of the sponsorship arrangement;

the term of the sponsorship and any conditions regarding renewal;

consequences of change which may occur over time e.g. a shift in the relationship, new policies, new corporate missions or objectives;

financial accountability requirements;

an indemnity by the sponsor against all liability for personal injury and for loss or damage costs, claims and expenses however caused or incurred as a result of any act of negligence by the sponsor;

provision for termination or suspension of the agreement.

The agreement must include a statement that that the Council’s functions will continue to be carried out fully and impartially, notwithstanding the existence of a sponsorship arrangement.

# Transparency

All Sponsorship Agreements are to be listed in the NHS-R Community’s Annual Report

# Approval of Agreements

All sponsorship bids shall be approved by the Director of the NHS-R Community in consultation with members of the TAG.

It is recommended that all potential sponsors are referred to this policy.

# Access to Policy

The Sponsorship Policy is to be placed on the NHS-R Community’s website.

# Disclaimer

Acceptance of advertising or sponsorship does not imply any endorsement of the sponsor’s products or services by the NHS-R Community

# Conflict of Interest

Board members are required to declare in advance if they have any personal interests, involvement or potential conflict of interest with any potential sponsor. 
In the event of a potential conflict of interest, member will take no part in the consideration of sponsorship with that particular NHS-R Community.

# Policy Review

This policy is subject to continuous review and will be reviewed on an annual basis. 

Date agreed: 9th February 2021