---
date: "2024-02-16T09:00:00+00:00"
title: "NHS-R Constitution"
---

# Our aims

To promote the adoption and use of R in the NHS specifically and the health and care sector more widely.

To deliver analytical and training solutions which are developed once and used often, and are feely available.

To facilitate the adoption of robust and appropriate analytical techniques which are independent of commercial statistical software packages.

To support open source software initiatives generally.

# Our values

The NHS-R Community provides a comprehensive service, available to all and is based on the same values as the NHS.

The NHS-R Community is committed to the principles of openness and transparency and collective ownership of analytic solutions.

The NHS-R Community aspires to the highest standards of excellence and professionalism.

The patient will be at the heart of everything the NHS-R Community does.

The NHS-R Community works across organisational boundaries, both public, voluntary, and private sector.

The NHS-R Community is committed to providing best value for funders money.

The NHS-R Community is accountable to the funder, the steering group, its members, the public, communities and patients that it serves.

# Membership policy

Membership is free and open to anyone who aligns with the aims and objectives of the NHS-R Community but is subject to members complying with our code of conduct. 
Members who fail to comply may be temporarily or permanently barred from the community subject to a review by two independent people from Steering Group and/or TAG.

A key principle of the NHS-R Community is its open source ethos. 
This means that any activity deemed to be counter to this ethos (for example engaging with the community primarily for commercial interests) is strictly prohibited.