on:
  workflow_call:

jobs:
  build-site:
    runs-on: ubuntu-latest
    if: github.event.pull_request.state != 'closed'
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libxml2-dev

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "downlit", "xml2"))'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-site
          path: _site