# Simple workflow for deploying static content to GitHub Pages
name: Preview Quarto page to GitHub Pages

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed


jobs:
  # Single deploy job since we're just deploying
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libxml2-dev

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "downlit", "xml2"))'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.8
        with:
          source-dir: ./_site/
