# Simple workflow for deploying static content to GitHub Pages
name: Publish Quarto page to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  publish-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Checkout gh-pages branch as _site worktree
        run: |
          git fetch origin gh-pages:gh-pages
          git worktree add _site gh-pages

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libxml2-dev

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "downlit", "xml2"))'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: Update gh-pages branch
        run: |
          pushd _site
          
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Stage changes
          git add .

          # Only commit if there are changes
          if ! git diff --cached --quiet; then
            git commit -m "Rendered site"
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi

          popd
