name: Publish Quarto page to GitHub Pages

on:
  push:
    branches: ["main"]

concurrency: publish

jobs:
  build-site:
    uses: ./.github/workflows/build.yaml

  publish-site:
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - uses: actions/checkout@v4
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-site
          path: _site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site